### ISSUE TITLE
Accès au géoppy sur le terrain

### ISSUE THREAD

**Issue by bobo-romania** [jancelin/geo-poppy#11]
Bonjour,
petite question que je n'ai pas réussi à résoudre tout seul.
Comment est ce que je peux me connecter à lizmap quand je suis sur le terrain? 

Lorsque le raspberry est connecté au réseau, j'y accède sans soucis mais dès qu'il n'est plus sur le réseau de mon routeur, plus moyen d'y accéder. 

j'ai testé des nmap pour voir les ports mais cela ne donne rien. De ce que j'ai compris, le raspberry est en mode hotspot

**Comment by jancelin** [comment]
Salut.

Tu n'a pas remarqué que tu as un réseau wifi geopoppy_rpi3?
tu t'y connecte mdp: geopoppy
et tu tape l'adresse 172.24.1.1

**Comment by jancelin** [comment]
https://github.com/jancelin/geo-poppy/blob/master/install/README_install_geopoppy.md

**Comment by bobo-romania** [comment]
Autant pour moi, je suis passé au travers.
Merci
