### ISSUE TITLE
Erreur durant le pull de postgis

### ISSUE THREAD

**Issue by MickaelH974** [jancelin/geo-poppy#12]
Bonjour,

Pendant le "docker-compose up  -d" lors du pull de postgis j'ai une erreur :

`ERROR: failed to register layer: symlink Marigot /var/lib/docker/overlay/d5e57a3820676e38f8d986f5166ac089dc68b2fe61ca459d4682c685096ba843/tmproot538982125/usr/share/zoneinfo/America/Guadeloupe: no space left on device`

Pourtant il me reste 2,6Go de disponible.

Je fait des test depuis Raspbian Jessie avec docker installé manuellement via la commande officielle:

`curl -sSL https://get.docker.com | sh`

**Comment by MickaelH974** [comment]
Je vais tester avec ton lien :

`docker pull jancelin/geopoppy:postgis`

**Comment by jancelin** [comment]
ça marche de ton côté?

**Comment by MickaelH974** [comment]
Bonjour,

Ca ne marchais pas malheureusement. Pas eu le temps de réessayer depuis désolé.
