### ISSUE TITLE
Chemins non définis pour le container pgadmin4

### ISSUE THREAD

**Issue by kagou** [jancelin/geo-poppy#13]
Lors de l'utilisation du container pgadmin4, l'utilisation d'outils comme import/export/backup/restore échouent avec un message d'erreur :
"Please configure the PostgreSQL Binary Path in the Preferences dialog."

En effet les préférences de pgadmin4 ne sont pas renseignées pour les chemins. 

A voir s'il est possible de les intégrer lors de la construction du container.

**Comment by jancelin** [comment]
Salut, 
c'est prévu dans la beta2 à venir bientôt.
Le container sera aussi en relation direct avec postgres via le docker-compose.yml

**Comment by Christophe55** [comment]
Bonjour jancelin, bonjour kagou

le chemin à renseigner est /usr/bin de mémoire
Par contre, jancelin, tu as supprimé pgadmin4 du docker-compose.yml de la dernière version 64 bits?

**Comment by jancelin** [comment]
Salut,
Je ne l'ai pas supprimé, c'est juste que je n'ai pas encore pris le temps de le mettre en container 64 bits.
Prochainement....
