### ISSUE TITLE
Sense-hat et fin d'un shutdown

### ISSUE THREAD

**Issue by kagou** [jancelin/geo-poppy#14]
Le souci avec l'utilisation du shutdown avec le sense-hat et le fait que ce dernier reste éclairé avec le symbole même après arrêt du PI3. Le symbole restant allumé l'utilisateur ne sait pas si le pi est effectivement arrivé au bout de sa procédure.

A voir donc la possibilité d'intégrer une ligne de commande bien placée afin que la toute dernière action du pi avant de s'éteindre et d'éteindre également le sense-hat.

**Comment by jancelin** [comment]
Prévu au programme, a venir....

**Comment by jancelin** [comment]
dev Sense-hat suspendu
