### ISSUE TITLE
Modification affichage sense-hat

### ISSUE THREAD

**Issue by kagou** [jancelin/geo-poppy#15]
Le système actuel permet de faire rapidement une erreur de manipulation.
Je propose donc que le système avec le stick fonctionne plutôt comme ceci :
click -> affichage des commandes
déplacement du stick -> selection/affichage de la commande souhaitée, lancement d'une temporisation. Attente du click de validation pour la commande, sinon au bout de la tempo on revient à l'arrêt/extinction du sense-hat

**Comment by jancelin** [comment]
C'est exactement ce que j'avais prévu, ça permettra d'avoir un menu plus complet et d'ajouter des fonctionnalités.
C'est en standby en ce moment car je me concentre sur le module de synchronistion des données. Le module SYNC

**Comment by jancelin** [comment]
N'hésite pas à contribuer @kagou

**Comment by kagou** [comment]
Je vais essayer :)

**Comment by jancelin** [comment]
dev Sense-hat suspendu
