### ISSUE TITLE
Copie simple sur la carte SD

### ISSUE THREAD

**Issue by Oros42** [jancelin/geo-poppy#17]
Proposition pour d'ajout dans /geo-poppy/install/README_install_geopoppy.md
Au lieu de passer par flash pour copier hypriotos-rpi-v1.4.0.img.zip sur la carte SD, voici une méthode beaucoup plus simple :
```bash
wget https://github.com/hypriot/image-builder-rpi/releases/download/v1.4.0/hypriotos-rpi-v1.4.0.img.zip
unzip -q hypriotos-rpi-v1.4.0.img.zip -d /tmp/
```
Brancher la carte SD.
/!\ remplacer <CARTE_SD>
```bash
sudo bash -c "cat /tmp/hypriotos-rpi-v1.4.0.img > /dev/<CARTE_SD>"
```
Puis utiliser ```gparted``` pour agrandir la dernière partition afin d'utiliser toute la carte SD.

**Comment by jancelin** [comment]
Salut,
je conseil ça maintenant, c'est telement simple et multi plateforme:

Flasher raspbian jessie sur une Micro SD avec ETCHER: https://etcher.io/

**Comment by jancelin** [comment]
MAJ wiki
https://github.com/jancelin/geo-poppy/wiki/2.-Installation-H%C3%B4te-et-param%C3%A9trage-wifi-direct
