### ISSUE TITLE
qgiserver url - SERVICE NON DISPONIBLE

### ISSUE THREAD

**Issue by CartONG-staff** [jancelin/geo-poppy#18]
Bonjour,

Tout d'abord merci pour cette superbe idée ! Nous avons utilisé GeoPoppy pour collecter des parcelles agricoles en Cote d'Ivoire (avec digitalisation en polygone sur tablette, lié à une table de propriétaires) et après un peu de bidouillage tout a fini par fonctionner (je vais rédiger une documentation sur notre projet, je la ferait suivre pour information).

Je tiens juste à remonter rapidement un bug que j'ai eu à résoudre. De manière relativement aléatoire je me retrouvais avec le fameux message "[SERVICE NON DISPONIBLE](https://www.google.fr/search?q=lizmap+SERVICE+NON+DISPONIBLE&rlz=1C1CHBF_frFR712FR712&source=lnms&sa=X&ved=0ahUKEwj097S4rv_WAhXDOhoKHSorC0sQ_AUICSgA&biw=1540&bih=760&dpr=1.25)" en background de Lizmap. Après un peu de recherche j'ai déduit que cela venait de Qgis Server et d'une requête WMS qui n'aboutissait pas.

J'ai ensuite constaté dans Portainer que les adresses IP des différents containers n’étaient jamais la même en allumant le rPi (elles sont générées à chaque démarrage et celle de qgiserver finissait parfois par 5 , parfois par 6). En prenant l'adresse IP de qgiserver et en la copiant dans l'URL du server WMS dans l'interface admin de Lizmap (c'est a dire, remplacer http://qgiserver/cgi-bin/qgis_mapserv.fcgi par http://[IP adresse du container qgiserver]/cgi-bin/qgis_mapserv.fcgi , j'arrivais à ne plus avoir le message d'erreur.

J'ai ensuite fixé les adresses IP des containers dans le docker-compose.yml en suivant cette méthode : https://stackoverflow.com/questions/39493490/provide-static-ip-to-docker-containers-via-docker-compose pour que qgiserver démarre toujours avec la même IP et je l'ai ecrite dans l'URL du server WMS de lizmap. Au final, plus de message d'erreur donc problème résolu ( ? ). Mais je ne suis pas sur d'avoir parfaitement cerné le soucis. Il y a bien un link entre lizmap et qgiserver dans le docker-compose.yml mais, dans mon cas, il ne fonctionnait que quand qgiserver s'allumait avec une adresse IP spécifique (en l’occurrence celle qui finit par 5).

Si quelqu'un a également rencontré ce problème ou pense à une façon plus propre de le résoudre je suis preneur ;)

Merci encore,

Léo

**Comment by jancelin** [comment]
Salut,

Bizarre, car le link permet justement de ne pas se soucier de l'IP car on remplace cette dernière par le nom du link.
J'ai déjà observé le "SERVICE INDISPONIBLE" suite à des problèmes de configuration de couches dans qgis  mais jamais à cause du link.
Peut tu essayer de rajouter 
```
depends_on:
      - qgiserver
```
dans la config de lizmap du docker-compose.yml. Au moins lizmap démarrera seulement si qgis server est fonctionel.

A vérifier....

**Comment by CartONG-staff** [comment]
Bonjour,

Merci pour le retour rapide, je vais essayer de remettre le link et de rajouter le depends_on et tester comme ça.

Je pensais aussi à une erreur des la configuration du projet ou des couches mais le caractère complètement aléatoire du message d'erreur me fait dire que le problème ne vient pas de là (quand le message d'erreur n’apparaît pas, aucun soucis pour ouvrir / éditer / exporter les couches).

Peut-etre que qgiserver se démarre mal, mais comme expliqué dans mon premier post, fixer les adresses IP a complètement résolu le problème (pour l'instant ...) et rien d’étrange dans les logs de portainer sur qgiserver quand le SERVICE INDISPONIBLE apparaît ...

- Leo

**Comment by l-martine** [comment]
Re-bonjour,

J'ai rajouté :
```
depends_on:
      - qgiserver
```
dans la config de lizmap du docker-compose.yml, et pour l'instant tout semble fonctionner. Je ferais un retour si le message d'erreur revient. 

Merci ;)

- Leo
