### ISSUE TITLE
antenne gps

### ISSUE THREAD

**Issue by sylvain0** [jancelin/geo-poppy#19]
Bonjour,

Déjà merci pour votre travail, j'ai vraiment hâte de pouvoir mettre cette solution en application!

Dans le cadre d'une amélioration de la précision gps des relevés je souhaiterais ajouter une antenne gps sur le raspberry.
Si vos essais RTK ont abouti, comment avez-vous configuré le système pour que la position enregistrée soit celle du raspberry et non pas celle du terminal (smartphone dans mon cas)?

Merci de m'avoir lu.

**Comment by sylvain0** [comment]
Rebonjour,
Je retente ma chance en reformulant!

L'utilisateur aura bien son raspberry pi dans la poche mais il effectuera la saisie depuis son smartphone.
Je compte brancher l'antenne GPS sur raspberry pi et j'ai donc un doute sur la position qui sera enregistrée, sachant que le smartphone n'est pas assez précis.
Ma question est alors de savoir si le paramétrage est possible (récupérer le x;y du raspberry pi) ou si je dois plutôt partir sur une solution intégrant un écran tactile au raspberry pi, par exemple?

Sylvain

**Comment by kikislater** [comment]
Bonjour,
Êtes vous allé faire un tour sur le wiki ? 
https://github.com/jancelin/geo-poppy/wiki/5.-GPS-Tracking

Une petite recherche dans un moteur de recherche donnera aussi ça : 
http://blog.geodatup.fr/utiliser-ses-coordonnees-gps-dans-lizmap.html
https://twitter.com/complementterre/status/640801827815063552

Avez-vous exploré ces pistes ?

**Comment by sylvain0** [comment]
Bonjour, et merci pour votre réponse!

Oui j'ai bien lu le wiki (pas les 2 autres) mais je dois manquer de connaissance et de vocabulaire pour bien tout comprendre!
En tous cas je n'arrive pas à savoir si l'installation du gpsd sur le raspberry suffit...

> gpsd est un démon de service qui surveille un ou plusieurs GPS ou récepteurs AIS connecté à un ordinateur hôte via les ports série ou USB, ce qui rend toutes les données sur l'emplacement / course / vitesse des capteurs disponibles pour être interrogé sur le port TCP 2947 de l'ordinateur hôte .

...et qu'on puisse relier sa position à l'objet créé via un formulaire sur un smartphone. En tous cas de ce que j'ai compris il y a des choses qui y ressembleraient!

Merci.

Sylvain

**Comment by kikislater** [comment]
La position doit pour moi être sur le raspberry et non sur le smartphone. 
Si la position est sur le smartphone, on peut switcher avec un module externe comme le reach. La procédure est détaillé ici avec une application tierce : https://docs.emlid.com/reach/common/tutorials/mock-location/

**Comment by sylvain0** [comment]
Merci encore pour votre réactivité.

> VO : (...) Also, it supports Android feature called mock location, which allows to substitute your device's built-in GPS receiver with an external location provider

> VF : (...) En outre, il prend en charge la fonctionnalité Android appelée emplacement fictif, qui permet de remplacer le récepteur GPS intégré de votre appareil avec un fournisseur de localisation externe

Ca a l'air d'être ça! Je testerai mais c'est pas pour tout de suite, le temps de tout mettre en place...

Merci!

**Comment by jancelin** [comment]
Salut,

Pour le modèle d'antenne compatible galileo: http://www.navilock.de/produkte/1286_GALILEO/62523/merkmale.html
Pour une antenne low cost en RTK: https://emlid.com/

Voici différentes possibilités de montage:

* antenne gnss usb sur le Raspberry: https://github.com/jancelin/geo-poppy/wiki/5.-GPS-Tracking
Je prévois de passer par un script python, mais c'est pas encore fait, voici la base de l'idée: https://raspberry-pi.developpez.com/cours-tutoriels/projets-rpi-zero/traceur-gps/

* antenne de la tablette / smartphone android: pas précis mais bon c'est pratique

* antenne externe connecté à la tablette/smartphone android:
** en usb: utilisation avec l'appli YouAreHere :https://play.google.com/store/apps/details?id=com.agbooth.usbgps&hl=fr
** en Bluetooth: avec l'appli BluetoothGPS: https://play.google.com/store/apps/details?id=googoo.android.btgps&hl=fr

**Comment by sylvain0** [comment]
Merci!

**Comment by sylvain0** [comment]
Re bonjour!

Je suis bloqué à "**Modifier le fichier gpsd.hotplug pour que ça hotplug**" dans `https://github.com/jancelin/geo-poppy/wiki/5.-GPS-Tracking`.
Le fichier est inexistant malgré une procédure d'installation effectuée sans encombres (apparents!).

Auriez-vous une piste?

Sylvain

**Comment by sylvain0** [comment]
...Si ça peut aider à la compréhension, ci-dessous, le message dans le terminal après la ré-installation où il me dit que tout se passe bien alors que je n'ai toujours pas de fichier _gpsd.hotplug_:
```
$ sudo apt-get install gpsd gpsd-clients python-gps
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gpsd is already the newest version.
gpsd-clients is already the newest version.
python-gps is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 33 not upgraded.
```

**Comment by kikislater** [comment]
A mon avis tout simplement parce que cette config est dépréciée et sûrement lié à ce commit : 
https://github.com/ukyg9e5r6k7gubiekd6/gpsd/commit/2db6137d7eb8d0ec7d0c1fb34e17dcb2f60b4f9d

Je penses qu'il vaudrait mieux poster sur le github en question pour plus de détail.

**Comment by sylvain0** [comment]
Merci pour les réponses et le temps que vous m'accordez!

Je ne suis pas sûr de bien comprendre! 
Je dois aller voir si un fichier correspondant aurait été créé autrepart (_/etc/defaults/gpsd_ ) ou lancer la commande `sudo dpkg-reconfigure gpsd`? (je ne peux pas travailler dessus avant qq jours).

Et petite info supplémentaire l'antenne BU-353-S4 n'était pas branchée pendant l'installation, je ne sais pas si ça joue...

**Comment by jancelin** [comment]
Désolé mais ça fait longtemps que je n'ai pas reproduit ma procédure d'installation, et je préfère la laisser de côté et repartir à neuf avec deux possibilités:
* si antenne sur pi: le script python (modifié) cité plus haut
* si antenne sur tablette: un futur script js sur lizmap
Je manque juste de temps pour le moment...

**Comment by kikislater** [comment]
Ici il y a post pour cette antenne gps : 
https://askubuntu.com/questions/30569/how-to-use-gps-receiver-bu-353
Même si ce n'est pas du Ubuntu, le fonctionnement est le même : base debian.

Editer le fichier /etc/default/gpsd et mettre ça : 


```
# Default settings for the gpsd init script and the hotplug wrapper.

# Start the gpsd daemon automatically at boot time
START_DAEMON="false"

# Use USB hotplugging to add new USB devices automatically to the daemon
USBAUTO="true"

# Devices gpsd should collect to at boot time.
# They need to be read/writeable, either by user gpsd or the group dialout.
DEVICES="/dev/ttyUSB0"

# Other options you want to pass to gpsd
GPSD_OPTIONS="-n -G -b"
GPSD_SOCKET="/var/run/gpsd.sock"
#end of file gpsd
```

**Comment by sylvain0** [comment]
Question de priorisation au boulot je laisse en suspens cette solution pour le moment et reste donc sur la configuration initiale, sans antenne.
J'y reviendrai, mais quand, je ne sais pas!
