### ISSUE TITLE
ssl-cert-snakeoil.pem : no start line

### ISSUE THREAD

**Issue by l-martine** [jancelin/geo-poppy#20]
Bonjour,

Après quelques temps d'utilisation d'un RaspberryPi, les couches provenant de PostGreSQL refusaient de s'afficher sur Lizmap (les couches en .shp marchaient toujours bien).

La connexion au port 5432 était devenue impossible (dans PGAdmin et QGIS) donc j'ai tenté de restart le composer postgis depuis portainer en lançant le script start-postgis.sh et est apparu cette erreur : 

![image](https://user-images.githubusercontent.com/9696676/33419391-7349a82c-d5aa-11e7-8b38-e5fbd90b1e0f.png)

`could not load server certificate file "/etc/ssl/certs/ssl-cert-snakeoil.pem" : no start line`

Effectivement, impossible de trouver ce fichier .pem à l'emplacement précisé. Je suis en train d'essayer de résoudre ça en me basant sur cette réponse : https://askubuntu.com/questions/49196/how-do-i-create-a-self-signed-ssl-certificate
 
Ma question est plutôt de savoir l'utilitée de ce .pem et quelles pourraient être les raisons de sa disparition soudaine (sachant que j'ignorais son existence et que je n'ai pas pu voir si il était bien là avant). Y'a t-il une date d'expiration ? 

Merci 

- Leo

**Comment by jancelin** [comment]
un petit 
```
docker-compose stop postgis
docker-compose rm postgis
docker-compose up -d postgis
```

**Comment by CartONG-staff** [comment]
Bonjour,

Super merci, ça résous bien le soucis. Une idée de pourquoi le script plante quand on le lance depuis la console de Portainer et surtout de ce qui fait que le bug arrive au premier abord ?

Merci
-Leo
