### ISSUE TITLE
[wiki] intégration tutoriel de configuration d'un projet Lizmap/QGIS/geopoppy

### ISSUE THREAD

**Issue by geodatup** [jancelin/geo-poppy#21]
Vois tu un inconvénient à merger cette [doc](https://github.com/CartONG/geopoppy_documentation/blob/master/README.md) avec le wiki ?

Je trouve dommage de ne pas mutualiser ces deux ressources "@complementterre"

si ok (des deux cotés) je ferais l'intégration

**Comment by jancelin** [comment]
Salut,
Avec plaisr. Merci pour le travail.
Ton script surface et date sont interressants, mais le faire sous postgresql/postgis via un trigger serai plus efficace je pense
Voici les exemples: 
https://github.com/jancelin/sql/blob/master/function_ocs_edition_perimetre_aire.sql
https://github.com/jancelin/sql/blob/master/function_current_date_auto_insert.sql

**Comment by CartONG-staff** [comment]
Salut,
Pas de soucis pour intégrer, on gardera tout de même notre version sur notre compte car il s'agit d'un des délivrables du projet. Après, la doc ne concerne au final que très peu GeoPoppy (du point de vue technique) mais surtout Lizmap et QGIS donc à voir si ça n'irait pas mieux là bas.
Merci pour les scripts, effectivement les miens ont été faits rapidement en .js (le calcul des surface est assez ... artisanal .. mais fonctionne :) )
- Leo

**Comment by geodatup** [comment]
Ok c'est `done` 
merci pour le partage de la doc. J'ai gardé les références aux images sur le dépot CartONG, et j'ai adapté et corrigé deux trois broutilles.

Pour les contributions, je pensais ajouter CartONG dans le _footer tel une liste ce qui donnera ceci 

* Julien ANCELIN 
* [CartONG](https://github.com/CartONG)

en conservant évidement le CC-by-sa

et je ne suis pas super convaincu de l'organisation final du TOC. A voir donc.

Si ok @jancelin je pense que tu peux fermer la question. ++

**Comment by jancelin** [comment]
le footer est modifié. Merci pour la contrib

**Comment by CartONG-staff** [comment]
Super, merci d'avoir prit le temps de fusionner les docs, le résultat valait bien le coup ;)
- Léo

**Comment by jancelin** [comment]
Bravo pour le déploiement de Geopoppy en Côte d'Ivoire, une belle surprise... et merci pour le tweet.
Au programme prochainement: plusieurs améliorations en cours dans l'edition de données (lizmap, merci 3liz) et dans la synchronisation des données multi-utilisateurs (Geopoppy Sync ).
Et vivement Qgis3 pour de nouvelles aventures.

**Comment by jancelin** [comment]
Salut @CartONG-staff est-il possible rajouter le crédit photo de l'illustartion de Geopoppy sur votre article d'aujourd'hui?:  Jordane ANCELIN CC BY SA
http://cartong.org/fr/news/suivi-de-la-d%C3%A9forestation-en-c%C3%B4te-d%E2%80%99ivoire-premi%C3%A8re-impl%C3%A9mentation-r%C3%A9ussie-de-l%E2%80%99outil-open
Merci bien pour l'article

**Comment by CartONG-staff** [comment]
@jancelin c'est indiqué dans le corps de la news en fait (on n'a pas de fonctionnalité "caption" sur notre site) : "schéma ci-contre (réalisé par Julien Ancelin, créateur de GeoPoppy"

**Comment by jancelin** [comment]
Justement, c'est ma femme qui l'a fait: Jordane ANCELIN  et non Julien

**Comment by CartONG-staff** [comment]
Pardon, j'ai lu trop vite ! Je corrige.
J'ai transféré ton email à Léo qui a fait toute la partie technique, mais comme il quitte CartONG début Janvier, je ne sais pas trop quel sera le suivi de notre côté.
Martin

**Comment by jancelin** [comment]
Merci,
je vais être embêtant mais le lien pointe vers moi à l'INRA plutot que vers le travail de Jordane https://pnr.parc-marais-poitevin.fr/pnr-equipe

**Comment by CartONG-staff** [comment]
Pas de souci, c'est moi qui fait 10 trucs à la fois et qui ne suis pas attentif. Corrigé !

**Comment by jancelin** [comment]
Merci
