### ISSUE TITLE
synchronisation bdd

### ISSUE THREAD

**Issue by sylvain0** [jancelin/geo-poppy#22]
Une autre question!

Dans votre [exposé ](https://webcast.in2p3.fr/video/presentation_de_solution_de_systemes_d_informations_embarques) vous dîtes à 19'28" : 
"...de retour au bureau on branche le rpi en ethernet ce qui enclenche un script de synchronisation vers le serveur central qui va mettre à jour des bases de type 'base terrain'(...)"
Je n'ai pas trouvé sur le wiki ou dans le tuto cartOng comment faire (à part avoir un UUID pour chaque table).

L'idée dans mon cas, qui me semble être identique au votre, serait d'avoir plusieurs opérateurs mais avec une base sur le serveur au bureau qui soit éditable et utilisable par le websig de ma collectivité.

Pouvez-vous m'orienter svp? encore :)

**Comment by kikislater** [comment]
Dans le répertoire Sync ici même tu as un readme ils qui explique.

**Comment by sylvain0** [comment]
Ok super merci !
