### ISSUE TITLE
Affichage projets

### ISSUE THREAD

**Issue by robinsonlucas** [jancelin/geo-poppy#24]
Bonjour,

Suite à mon installation réussie, je n'arrive pas à accéder au projet démo. L'interface de lizmap apparait bien à l'URL https://172.24.1.1/, et j'ai bien modifié le chemin d'accès aux répertoires locaux (/home/), mais aucun projet n'apparait. 
De plus, j'ai structuré une base de donnée personnelle et je l'ai configurée avec le plugin lizmap de façon à la publier, j'ai placé les fichiers dans les bons répertoires (/home/geopoppy/lizmap/project/) avec filezilla mais celle-ci n'apparait pas non plus dans les projets. J'ai bien sûr vérifié l'intégrité des dockers. 
D'ailleurs je ne comprends pas bien le fonctionnement de l'arborescence : l'application web lizmap renvoie un message d'erreur "Le chemin donné pour le répertoire n'existe pas sur le serveur" si j'essaie de spécifier le chemin d'accès aux repertoires locaux jusqu'au projet (/home/geopoppy/lizmap/project/).
J'ai formulé l'hypothèse que cela soit lié à des droits restreints de consultation, mais j'ai bien vérifié ces droits comme indiqué dans le tutoriel (chmod et chown).
Je n'arrive pas vraiment à voir d’où vient le problème....
Bref en tout cas la base de donnée embarquée est rudement pratique.

**Comment by Christophe55** [comment]
Bonjour,
Ayant souhaité évoluer vers la version 64 bits, je me retrouve avec le même problème, j'arrive bien à voir mes fichiers via cloud-commander, mais mon lizmap ne m'affiche aucun projet.

Mon projet s'est affiché après avoir lancer un chmod 777 -R sur le répertoire docker, ce qui je l'avoue n'es pas très orthodoxe.

**Comment by robinsonlucas** [comment]
Bonjour,
J'avais déjà fait cette manipulation mais sans succès pour ma part... Je réessaierai avec une nouvelle base dans quelques mois.

**Comment by jancelin** [comment]
/home/files/qgis/
