### ISSUE TITLE
Recommandation achat materiel pour Geo-poppy

### ISSUE THREAD

**Issue by clardeux** [jancelin/geo-poppy#25]
Bonjour,

je souhaiterais mettre en place GeoPoppy pour des relevés terrain sur base d'image Satellite et formulaire qgis.

Sur le git, bien qu'il y ai des recommandations de matériel générique, serait-il possible d'avoir des références/lien précis pour acheter le raspberry pi 3 et surtout le boîtier et kit pile et/ou batterie. Pour la carte sd pourquoi pas une référence mais c'est plus simple.

Merci d'avance et bravo pour ce travail.

**Comment by pierrechtux** [comment]
Bonjour,
Quelqu'un aurait-il l'idée de commercialiser un kit complet geopoppy? Avec le Pi quivabien, la batterie quivabien, la carte SD quidémarrebien et quitournebien, et éventuellement une configuration sur mesure?
(je rêve, mais bon, ça peut marcher, et ça pourrait intéresser du monde).
À+
Pierre
