### ISSUE TITLE
Erreur d'impression

### ISSUE THREAD

**Issue by Christophe55** [jancelin/geo-poppy#26]
Bonjour jancelin,
je me delecte de la nouvelle version pour RPI3 en 64bits, par contre j'ai un problème récurent lors de la génération des impressions, il me provoque une erreur en affichant la parge suivante : 

`Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
Apache/2.4.25 (Debian) Server at qgiserver Port 80`

sais-tu d'ou le problème peut venir?
un manque pilote pour le serveur apache.
L'erreur se produit quelque soit le format de fichier d'impression choisi.

@ plus et encore merci pour ton travail

**Comment by jancelin** [comment]
ok sur serveur, mais pas encore de compil sur rpi....
ça arrive à la fin du mois d'aout

**Comment by jancelin** [comment]
https://github.com/jancelin/docker-qgis-server/commit/11dede156b62f98883e1832bf8f69e9b45cd59c8#diff-3254677a7917c6c01f55212f86c57fbf
