### ISSUE TITLE
Base de données "postgis" exit  hors connexion

### ISSUE THREAD

**Issue by CorentinFalc** [jancelin/geo-poppy#27]
Actuellement un problème est rencontré lors du redémarrage du container "postgis" sur le raspberry lorsque celui-ci est en mode "Hors-Connexion", à la suite de la commande "docker-compose up".
   Ce problème est dù au "entrypoint" du container "postgis", qui tente de télécharger des fichiers situés sur le web. Ne pouvant pas se connecter, le fichier est introuvable et le processus s'arrête sans aboutissement. Le container "postgis" ne démarre pas et reste en exit.
    Pour pallier ce problème il suffit de commenter les lignes concernées par l'entrypoint en utilisant la commande "sudo nano docker-compose.yml" pour rentrer dans le fichier en édition, puis de rajouter le "#" et commenter les lignes.
  Résultat ci-dessous:
  ```#
#Comment entrypoint after first boot
  #    entrypoint: >
  #      bash -c "wget -N -P / https://raw.githubusercontent.com/jancelin/docker-postgis/master/setup-database.sh &&
  #               wget -N -P /home https://github.com/jancelin/docker-postgis/raw/master/geopoppy.sql &&
  #               /docker-entrypoint.sh"
```
Une fois cette action réalisée, il est possible d'utiliser la commande "docker-compose up -d" pour démarrer à nouveau les container. Le containter postgis sera bien en état de marche et il ne sera plus nécessaire de modifier le fichier par la suite.

Ce bug est identifié et sur le point d'être résolu. En attendant, il faut penser à éditer le fichier docker-compose.yml juste après la première installation.

**Comment by jancelin** [comment]
https://github.com/jancelin/geo-poppy/pull/28
