### ISSUE TITLE
Certificate error at first connection

### ISSUE THREAD

**Issue by pierrechtux** [jancelin/geo-poppy#34]
After an installation from scratch of geopoppy, when I try to connect to the lizmap configuration page:
    https://black-pearl.local/websig/lizmap/www/admin.php/admin/config/

I get this message:

> La connexion n’est pas sécurisée
> Les propriétaires de black-pearl.local ont mal configuré leur site web. Pour éviter que vos données ne soient dérobées, Firefox ne s’est pas connecté à ce site web.
> En savoir plus…
> Signaler les erreurs similaires pour aider Mozilla à identifier et bloquer les sites malveillants
> black-pearl.local uses an invalid security certificate.
> The certificate is not trusted because it is self-signed.
> The certificate is not valid for the name black-pearl.local.
> Error code: SEC_ERROR_UNKNOWN_ISSUER

No big deal.  I had similar issues on my server, which I addressed by letsencrypt.
Note that I'm not going through the wifi, which is not properly working on my client machine, but ethernet seems to be okay.

**Comment by CorentinFalc** [comment]
Hi,
Indeed, for the first access to the web page you need to add an exception. 
We've add that tip to the wiki in order to prevent user from that issue.
