### ISSUE TITLE
First connection to geopoppy: unknown username / password

### ISSUE THREAD

**Issue by pierrechtux** [jancelin/geo-poppy#35]
I just realised that I may as well speak^Wwrite in French...

Donc j'ai fini l'installation, enfin, du geopoppy sur mon Pi, et, une fois le souci de certificat mis de côté, j'ai suivi les dernières instructions données par le script, à savoir:

> * Connectez-vous ensuite au réseau wifi GeoPoppy_Pi3
>  Mot de passe: geopoppy

Là, tout va bien, en accédant avec mon téléphone (un ordiphone android); le wifi a toujours déc0nné sur mon ordi, de sorte que je n'ai même pas essayé de me connecter au Pi depuis l'ordi.

>  Puis taper l'adresse https://172.24.1.1 dans votre navigateur web pour accéder à la démo

Sur le téléphone, tout va bien, ça amène à une page vide avec, en haut, un bandeau "Projets - Demo", et à droite, un bouton 1/0 et "Connexion".
Un logo "Powered by 3Liz" figure en haut à droite.
Et voilà tout.

En tentant de me connecter, j'ai essayé avec peu d'inspiration, quelques mots déjà utilisés: docker - docker , geopoppy - geopoppy , michu - admin ... en vain.

>  IL FAUT PARAMETRER LIZMAP!!!! https://172.24.1.1/websig/lizmap/www/admin.php/admin/config/

Toujours depuis mon téléphone, j'arrive sur une page qui me demande un login; j'ai essayé, avec aussi peu d'inspiration, et sans plus de succès.

Las, j'ai été voir par là, mais avec mon ordi, en passant par:

`	firefox black-pearl.local`

Ce qui fonctionne fort bien.
Du coup, j'ai été voir par ici:

	firefox black-pearl.local/websig/lizmap/www/admin.php/admin/config/

Mais cela aboutit à la même page, et cela n'aide guère, sauf à clavioter confortablement, en essayant encore plus de username-passwords. Hélas, sans plus de succès.

> * Connection Data Base avec PgAdminIII ou Qgis 172.24.1.1:5432, base: geopoppy , login et mot de passe: docker

Impeccable, même deux. J'apprécie les conventions de nommage des tables, j'ai souvent recours à des vocabulaires similaires.

> * Déposer ses projets Qgis ici:  http://172.24.1.1:8000/fs/mnt/fs/files/qgis/ 
 
> en wifi direct: 
> 172.24.1.1                >> lizmap / qgiserver 
> 172.24.1.1:5432           >> postgresql 

=> pas tenté

> http://172.24.1.1:9000    >> portainerio : renseigner un mot de passe a la premiere connection + 
> section locale

=> ah, je me suis dit que c'est là qu'il fallait créer un username et password qui aille bien: j'ai donc fait un tel utilisateur, et ai tenté de me logger avec, aux URL supra: sans succès.

Une fois le compte créé, j'arrive sur une page de portainer (http://black-pearl.local:9000/#/init/endpoint) où j'ai un choix entre manager un environnement docker local, remote, agent ou azure. Et là, je ne sais que faire. Je suis assez puceau du docker.

> http://172.24.1.1:8000/fs/mnt/fs/files/qgis/    >> cloudmanager: dépot de fichier: login admin mdp 
> admin

=> pas tenté

**Comment by AndreasRey** [comment]
Salut, perso j'ai pu me connecter avec les credentials par défaut de Lizmap avec succès :
- login : admin
- mdp : admin

**Comment by CorentinFalc** [comment]
Bonjour,
Les identifiants de connexion pour Lizmap sont bien admin/admin.
Nous les avons ajoutés dans le wiki ainsi que les liens et identifiants des autres conteneurs.

**Comment by pierrechtux** [comment]
Alors, en effet, je réussis à me connecter avec admin et admin; mais je n'ai qu'une malheureuse page blanche (à part le bandeau du haut et une icône à droite en haut) qui s'ouvre.

J'ai essayé avec firefox et chromium, même résultat.

Est-ce normal, docteur? Qu'ai-je loupé?
