### ISSUE TITLE
Lizmap corruption data base à cause du mode édition

### ISSUE THREAD

**Issue by Zargith** [jancelin/geo-poppy#46]
Bonjour, je suis toujours en train de mettre en place Geopoppy et en faisant mes tests au fur et à mesure que j'avance. Je me rends compte que le mode édition des maps via Lizmap corromp les data bases. Pourquoi, je ne sais pas. J'ai pu voir cela en voulant rééditer mes layers dans une data base de test via QGIS.

Comme message d'erreur, j'ai le droit a tout ça :

>Layer is not valid: The layer dbname='test-database' host=172.24.1.1 port=5432 user='docker' password='docker' sslmode=allow srid=0 type=MultiPoint table="public"."test-points" (geom) sql= is not a valid layer and can not be added to the map

Dans le log panel j'ai ça :

Panel processing :
> Problem with SAGA installation: SAGA was not found or is not correctly installed

(Pourtant j'ai vérifié SAGA est bien instalé et a jour autant sur mon pc que sur le raspberry)

Panel PostGis:
>Unable to access the "public"."test-polygones" relation.
			The error message from the database was:
			no result buffer.
			SQL: SELECT * FROM "public"."test-polygones" LIMIT 1

(Je ne connais rien au SQL je ne sais pas ce que je dois comprendre de ce message d'erreur)

Panel Python warning :
>warning:/home/[ME]/.qgis2/python/plugins/lizmap/lizmap.py:2177: DeprecationWarning: QgsMapCanvas.mapRenderer() is deprecated
			  pCrs = mc.mapRenderer().destinationCrs()
			traceback:  File "/home/[ME]/.qgis2/python/plugins/lizmap/lizmap.py", line 2991, in run
			    result = self.dlg.exec_()
			  File "/home/[ME]/.qgis2/python/plugins/lizmap/lizmap.py", line 2786, in getMapOptions
			    self.writeProjectConfigFile()

(Je ne connais pas non plus le Python donc je ne comprends pas non plus ce que je dois tirer du message d'erreur)

J'ai par ailleurs essayé de recréer une data base similaire à l'ancienne et tout fonctionnait bien jusqu'à ce que j'essaye d'éditer la map via Lizmap. Et lorsque j'essaye d'éditer les layers de la map ça charge à l'infini je ne sais pas pourquoi non plus.

Donc si quelqu'un a une idée pour m'aider je suis preneur !
Merci d'avance.

**Comment by jancelin** [comment]
Salut,
En premier j'essayerai de ne pas utiliser de "-" dans Postgresql, mais un "_".
Si le problème persiste relancez moi ici.
Vous utilisez l'image flashable ou l'install par ligne de commande ?

**Comment by jancelin** [comment]
Attention !
Pour utiliser pleinement GeoPoppy (postgresql/Postgis/qgis/lizmap) il est nécessaire d'avoir des compétences sur Postgresql et en SQL...

**Comment by Zargith** [comment]
Bonjours,
Depuis ce matin je fais plein de tests à la main et pour une raison obscure je n'ai plus le problème de corruption de mes data bases...
J'ai essayé d'utiliser des '_' plutôt que des '-' et ca n'a rien changé. Donc ça fonctionne maintenant juste en partant le weekend sans y toucher. Je peux même éditer les layers via Lizmap sans soucis!

Je pense que l'on peut close cette issue du coup, je l'a réouvrirai si jamais le problème refait surface!

**Comment by jancelin** [comment]
Salut, 
Bonne nouvelle :) 
Merci pour le retour
