### ISSUE TITLE
Perte droits admin sur Lizmap

### ISSUE THREAD

**Issue by Zargith** [jancelin/geo-poppy#47]
Bonjour,

Je viens de me rendre compte que je n'ai plus accès aux droits administrateur sur Lizmap alors que je suis connecté comme tel. Je ne sais pas a quel moment cela s'est produit car j'avais pu créer un nouvel utilisateur mais je n'ai pas plus de droits que lui étrangement.
Une petite idée de ce que ça pourait être?

Merci d'avance!

**Comment by jancelin** [comment]
salut,
pas d'idée....
la solution est de modifier le fichier /home/pirate/docker-compose.yml et de changer le volume ou est situé les fichier de conf.
```
 volumes:
     - project:/home
#     - var:/var/www/websig/lizmap/var
     - var1:/var/www/websig/lizmap/var
```
de rajouter le volume à la fin du fichier:

```
volumes:
   portainer:
   postgres:
   redis:
#   var:
  var1:
  project:
```
et de relancer le container lizmap:

```
docker-compose up -d lizmap
```
Ca repartira à neuf

**Comment by Zargith** [comment]
Bonjour,

J'ai fais les changements que vous m'avez conseillé eca message est apparru:

> WARNING:
Service "lizmap" is using volume "/var/www/websig/lizmap/var" from the previous container. Host mapping "pirate_var1" has no effect. Remove the existing containers (with `docker-compose rm lizmap`) to uRecreating pirate_lizmap_1 ... done

J'ai donc suivi ce que me disait ce message et ai rentré la commande puis relancer `docker-compose up lizmap`.

Par contre il boucle infini sur ce dernier message:

> lizmap_1     | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.7. Set the 'ServerName' directive globally to suppress this message

Cependant le container a bien été relancé et Lizmap a bien été réinitialisé.

Merci beaucoup!

Si jamais le bug revient je le remonterai à nouveau ici.
