### ISSUE TITLE
Problème de publication de projet

### ISSUE THREAD

**Issue by NykoTera** [jancelin/geo-poppy#49]
Bonjour,
J'ai voulu essayer geopoppy en me basant sur mes maigres connaissances en raspberry et j'ai été bluffé de voir que j'avais presque réussi aller au bout de la procédure. Le souci que je remonte viens de la connexion avec Filezilla pour publier le projet sur le raspberry. En fait la connexion ftp ne souhaite tout simplement pas se faire. Voilà les infos que me retourne filezilla : 
```
Statut :	Connexion à 172.24.1.1...
Réponse :	fzSftp started, protocol_version=8
Commande :	open "pirate@172.24.1.1" 22
Commande :	Pass: *******
Erreur :	Échec de l'authentification.
Erreur :	Erreur critique : Impossible d'établir une connexion au serveur
```

Après plusieurs essais, il me semble pourtant avoir bien entré les identifiants, pass et port indiqués sur le wiki ([https://github.com/jancelin/geo-poppy/wiki/3.4.-Publication-du-projet-sur-le-RaspberryPi-par-FTP](url)).

Savez-vous d'où provient l'erreur?

D'avance merci.

Nicolas

EDIT : Bonjour,
Je reviens vers vous parce que la situation semble avoir évolué. En fait j'ai essayé la solution d'installation from scratch. Et là j'ai presque réussi à faire le transfert par ftp.
Mais je n'ai pas pu car le dossier /home/GeoPoppy/lizmap/project n'existe pas. Le plus étrange c'est que je voie les projets "démo" lorsque je me connecte sur l'ip du raspberry avec une tablette ou un ordinateur...

D'avance merci pour vos retours.

**Comment by Zargith** [comment]
Hello!

Pour ma part j'avais trouvé après pas mal de recherches, où se trouvent les fichiers que va chercher Lizmap. Et j'ai finalement trouvé ici: `/var/lib/docker/volumes/pirate_project/_data/files/qgis/`.
Dans Lizmap le chemin pour les projets demo est `/home/files/qgis/`.
Donc `/home/` = `/var/lib/docker/volumes/pirate_project/_data/`.
Libre à vous de configurer les dossiers à la main si vous trouvez ça plus simple comme moi. :)

**Comment by Zargith** [comment]
Effectivement que tu ne puisse pas déplacer des fichiers quand tu vas dans le dossier `var`, pour cela il faut être en `root mode`.
De plus, lorsque je fais la manip, je la fais depuis un terminal. Je me connecte en SSH au raspberry, tape `sudo su` (pour activer le mode `root`) et je copie mes fichiers que j'aurais préalablement mis sur le raspberry grâce un FTP tel que `FileZilla`! ;)

Sinon, non il ne faut pas nécessairement d'image .png pour que le projet apparaisse sur Lizmap.

Quant à tes containers, moi aussi j'avais eu ce problème et le première fois j'ai réinstaller tout geopoppy (et oui j'y connais rien à Docker x)), la fois suivant un ou deux redémarrage ont suffit. ¯\_(ツ)_/¯
