### ISSUE TITLE
Bug utilisation Geopoppy hors connection

### ISSUE THREAD

**Issue by Zargith** [jancelin/geo-poppy#53]
Bonjour,

Je remonte un bug que j'ai trouvé, et qui persiste sans que je comprenne pourquoi. Ce qu'il se passe, c'est lorsque je veux charger un projet et que je sui hors connexion, j'ai ça  qui apparait :
![screenshot_20181023-113558](https://user-images.githubusercontent.com/36247975/47365739-7fcb9e00-d6dc-11e8-83f2-7c16eed99d1b.png)

J'ai beau appuyer sur `fermer`, ça ne change rien.

Du coup je dois brancher un câble ethernet, relancer la page et une fois qu'elle est chargée, je peux débrancher le câble.

Cependant, ça n'arrive pas avec les projets démo, seulement avec les projets que j'ai créé. Je ne pense pas avoir mal fais quelque chose car j'ai suivis plutôt à la lettre le wiki.

J'ai même créé une nouvelle base de données et un nouveau projet pour être sûr qu'il n'y ai rien de corrompu mais rien à faire, le problème persiste...

Je fais avec pour l'instant mais c'est assez pénible de pas avoir trouvé d'où ça peut venir.

Si jamais quelqu'un a une idée, je suis preneur!

PS: dans les logs j'ai ça: `error	Spatialite is not available`, j'ai cherché sur internet d'où ça pourrait venir mais je n'ai pas trouvé de réponse qui fonctionne... :/

**Comment by jancelin** [comment]
si ça marche avec un cable ethernet branché c'est que l'adresse de postgres ne doit pas être la bonne.
il faut créer les projets qgis (connexion postgres)avec l'ip 172.24.1.1 port 5432 pour qu'il trouve bien la base postgresql.
Dans tout les cas si les projets démo fonctionnement c'est que c'est la conception de ton projet qui bloque.

**Comment by Zargith** [comment]
Pourtant l'adresse postgres est bien celle que vous m'indiquez.
Je ne pense pas avoir mal fait quelque chose mais pour être sur je vais quand même décrire comment je m'y prend.

- Dans un premier temps je me connecte au wifi du raspberry avec mon pc, ouvre une page pgadmin et me connecte au serveur du raspberry.
- Ensuite soit je créé une nouvelle base de donnée ou créé un schéma sur base existante.
- Je créé ensuite un projet qgis, je me connecte à la base de données avec l'ip 172.24.1.1, le port 5432 et la base sur laquelle je veux travailler.
- J'ouvre le plugin DB Manager et sélectionne le schéma sur lequel je veux travailler.
-J'ouvre ensuite la fenêtre de requêtes SQL et rentre les commandes l'une à la suite de l'autre: `CREATE EXTENSION POSTGIS`, `CREATE EXTENSION POSTGIS_TOPOLOGY`. (Sauf si je l'ai déjà fais via pgadmin ou que je l'ai fais pour un autre schéma).
- Je créé une nouvelle table en commençant par ajouter l'élément id de type serial et le définit en tant qu clé primaire. J'ajoute les colonnes dont j'ai besoin, je coche les deux cases pour créer une colonne géométrique et un index spatial.
- J'ajoute la couche nouvellement créée au projet et créé un premier point. Je sauvegarde la couche puis je met la "sous-couche", créée après la sauvegarde de la couche précédemment éditée, sur le projet et enlève l’ancienne.
- J'ajoute le couche dans propriétés du projet -> capacités WFS puis j'ajoute la couche dans le plugin lizmap en tant que couche éditable.
- Je sauvegarde et transfère le projet sur le raspberry grâce à FileZilla.
- Je m'assure ensuite que le rasberry n'est pas relier au câble ethernet et me connecte avec une tablette via un navigateur internet a lizmap (en étant préalablement connecté en wifi au raspberry).

J'ouvre le projet mais toujours le problème... :/

Quand le câble ethernet est branché le problème n'apparait pas et je peux ajouter des éléments, à la couche, en supprimer et modifier.

Après ce que je fais pour pouvoir voir voir apparaitre les nouveaux éléments, c'est premièrement créer un nouvel élément. Retourner sur qgis et comme une nouvelle "sous-couche" s'est créée, je supprime les éléments de la première "sous-couche" (pour pas les voir apparaitre dans la table attributaire et parce que je ne peux pas mettre les deux "sous-couches" en même temps, une seule dont les éléments apparaissent mais bien indiqué que deux couches sont présentent et quand j'en décoche une (pour plus la voir) ça décoche l'autre avec donc elles sont lié c'est évident mais on ne peut pas voir les éléments des deux en même temps).
Suite à la suppression de de la première "sous-couche" je répète ce que j'avais fais pour la première "sous-couche" mais à la deuxième (WFS coché, plugin lizmap, etc...).
Ensuite je peux éditer la couche et voir apparaitre les ajouts et les changements d'éléments en direct mais si je débranche le câble avant de relancer le projet, le problème persiste.

J'espère avoir été pas trop dispersé dans ma description de comment je m'y prends et que ça aidera. Car tout me semble bien mais je peux faire une erreur et juste ne pas le savoir aussi ^^'

**Comment by jancelin** [comment]
Pouvez vous créer un projet qgis avec la table inventaire_gps de la base géopoppy afin de voir si ça viens de votre base postgresql ou d'autre chose?

**Comment by Zargith** [comment]
Bonjour, je n'ai pas de table inventaire_gps dans la base geopoppy et je n'ai rien trouvé qui y réfère parmi les fichiers sources. Je me suis dis que c'était peut être ça https://github.com/jancelin/geo-poppy/blob/dev/tracking/trame.sql donc j'ai créé une table avec ce code SQL mais ça n'a rien changé.

Si ce n'était pas cette table (créée avec ce code SQL), comment puis-je l'obtenir?

**Comment by Zargith** [comment]
Bonjour, je pense avoir résolu le problème!
L'idée a surgi tout à coup dans mon esprit sans raison particulière. J'ai simplement mis à jour chaque container Docker en rentrant à l'intérieur et tous les projets fonctionnent hors connexion!

J'espère que ça venait de là le problème comme ça je ne serai plus embêté par celui-ci!
Merci quand même pour l'aide! :)
