### ISSUE TITLE
Problème lors de l'installation

### ISSUE THREAD

**Issue by arteragence** [jancelin/geo-poppy#55]
Bonjour,

Après plusieurs hésitations liées à mes faibles connaissances dans ce domaine,  j'ai décidé de passer le cap et de tenter l'aventure Geopoppy. J'ai donc acheté un rasberry pi 3 (modèle b+) et suivi le wiki pour l'installation.
L'installation se déroule bien malgré le symbole de l'éclair et le message d'erreur indiquant régulièrement une baisse de tension. J'ai testé sur secteur, batterie externe et cela ne change pas. J'ai donc commandé l'alimentation secteur officielle pour voir si cela change quelque chose.
Après l'installation je parviens à me connecter au réseau Geopoppy mais impossible d'accéder aux adresses du wiki (j'ai testé par wifi et ethernet, aucun résultat).
J'ai fait plusieurs test, en reflashant la carte pour partir de zéro, et bloque toujours au même point.
En essayant de raisonner logiquement je me dis que le problème peut venir :
- du modèle du raspberry lui même, Geopoppy peut-il fonctionner avec un modèle B+ ou faut-il obligatoirement un modèle B ?
- les baisses de tension empêchent une bonne installation de Geopoppy d'où les problèmes survenant après. 
- j'ai fait une erreur lorsque j'ai flashé la carte mais Etcher ne détecte aucun problème lors de la vérification...

À ce point de ma réflexion je m'en remet à votre expérience car je vous avoue être en train de piétiner pour le moment.

Je vous remercie par avance et m'excuse pour le texte un peu long, je souhaitais être le plus précis possible.

Laurian

**Comment by pierrechtux** [comment]
Bonjour,
Je rencontre des soucis similaires: je vois que votre ticket a été clos le jour même, ce qui est encourageant. Comment fut-ce résolu, de votre côté?

**Comment by Ailurupoda** [comment]
#56 
Bonjour,
Le problème provient principalement de l'alimentation et du fait que l'installation n'arrivait pas à se terminer correctement il me semble.

**Comment by arteragence** [comment]
Bonjour,

J'avais posté un doublon sans le vouloir d'où la fermeture le jour même.
Après avoir acheté l'alimentation "officielle" raspberry et relancé l'installation cela a marché. A la réflexion je me demande si je n'ai pas été trop impatient lors de l'installation. Mon conseil serait d'utiliser une bonne alimentation, de lancer l'installation et de ne pas hésiter à attendre longtemps pour être sur et certain que l'installation soit finie avant de tenter la connexion en wifi (la led ne doit vraiment plus clignoter).

Bon courage.
