### ISSUE TITLE
Problème à l'installation (accès a Lizmap)

### ISSUE THREAD

**Issue by arteragence** [jancelin/geo-poppy#56]
Bonjour,

Après plusieurs hésitations liées à mes faibles connaissances dans ce domaine,  j'ai décidé de passer le cap et de tenter l'aventure Geopoppy. J'ai donc acheté un rasberry pi 3 (modèle b+) et suivi le wiki pour l'installation.
L'installation se déroule bien malgré le symbole de l'éclair et le message d'erreur indiquant régulièrement une baisse de tension. J'ai testé sur secteur, batterie externe et cela ne change pas. J'ai donc commandé l'alimentation secteur officielle pour voir si cela change quelque chose.
Après l'installation je parviens à me connecter au réseau Geopoppy mais impossible d'accéder aux adresses du wiki (j'ai testé par wifi et ethernet, aucun résultat).
J'ai fait plusieurs test, en reflashant la carte pour partir de zéro, et bloque toujours au même point.
En essayant de raisonner logiquement je me dis que le problème peut venir :
- du modèle du raspberry lui même, Geopoppy peut-il fonctionner avec un modèle B+ ou faut-il obligatoirement un modèle B ?
- les baisses de tension empêchent une bonne installation de Geopoppy d'où les problèmes survenant après. 
- j'ai fait une erreur lorsque j'ai flashé la carte mais Etcher ne détecte aucun problème lors de la vérification...

À ce point de ma réflexion je m'en remet à votre expérience car je vous avoue être en train de piétiner pour le moment.

Je vous remercie par avance et m'excuse pour le texte un peu long, je souhaitais être le plus précis possible.

Laurian

**Comment by arteragence** [comment]
Bonjour,

A priori problème résolu suite à un nouveau test de réinstallation avec l'alimentation officielle Raspberry. Je n'ai eu aucun message de problème de tension. Il s'agit peut-être d'un point important : prévoir une alimentation correcte lors de l'installation.
Je laisse le sujet ouvert quelques jours si jamais vous pensez que le problème venait d'ailleurs ou souhaitez apporter des précisions.

Laurian

**Comment by jancelin** [comment]
Merci pour le retour, c'est un point important que j'avais oublié de préciser dans le wiki matériel,
C'est modifié:
https://github.com/jancelin/geo-poppy/wiki/1.--Mat%C3%A9riel
