### ISSUE TITLE
Réveil difficile: docker semble inopérant

### ISSUE THREAD

**Issue by pierrechtux** [jancelin/geo-poppy#60]
Bonjour,
J'ai un Pi avec un GeoPoppy qui tournait tranquillou, à 800km d'ici.
Suite à une coQuille d'alimentation, il a redémarré... brutalement, disons.
Il a perdu l'heure sans arriver à joindre de serveur ntp (pas grave, je m'en suis débrouillé), et il ne répond plus aux URL habituelles.

En ssh, on s'aperçoit vite que pas mal de choses du côté de docker ne semblent pas tourner:
```
  # root@geopoppy: ~        < 2019_03_07__17_45_05 >
docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

  # root@geopoppy: ~        < 2019_03_07__17_45_05 >
```
Quid? Les précieux conteneurs auraient-ils disparu?

De toute évidence, il y a du monde, en fouinant un peu:
```
  # root@geopoppy: ~        < 2019_03_07__17_45_05 >
du -sh /var/lib/docker/*
20K     /var/lib/docker/builder
336K    /var/lib/docker/containerd
264K    /var/lib/docker/containers
14M     /var/lib/docker/image
88K     /var/lib/docker/network
4.1G    /var/lib/docker/overlay2
20K     /var/lib/docker/plugins
4.0K    /var/lib/docker/runtimes
4.0K    /var/lib/docker/swarm
4.0K    /var/lib/docker/tmp
4.0K    /var/lib/docker/trust
180K    /var/lib/docker/volumes

```

Mais comment donc les redémarrer?
J'ai tenté le script suivant, qui me semblait de bon aloi, mais sans succès apparent:
```
  # pirate@geopoppy: ~        < 2019_03_07__17_53_36 >
./check_docker.sh 

  # pirate@geopoppy: ~        < 2019_03_07__17_53_36 >
docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

  # pirate@geopoppy: ~        < 2019_03_07__17_53_36 >
```

Et surtout, qu'aurais-je donc fait de si mal pour que mon pauvre GeoPoppy s'en trouve si fâché, lui qui tournait si bien?

(je précise que je me dépucèle peu à peu du docker: c'est assez laborieux)

**Comment by pierrechtux** [comment]
Ça a fonctionné, merci!

Et du coup, j'ai mis ça dans le `/etc/rc.local` , manière de m'épargner d'autres surprises du même genre.

**Comment by pierrechtux** [comment]
Je clos l'issue, bien que je me demande encore comment cela a pu survenir.
Dans quels logs pourrais-je trouver des indices?

**Comment by jancelin** [comment]
ok, je ferme
