### ISSUE TITLE
Perte de connexion lors de la saisie de données

### ISSUE THREAD

**Issue by arteragence** [jancelin/geo-poppy#62]
Bonjour,

Il m'est arrivé à deux reprises aujourd'hui de perdre l'accès au Geopoppy, que ce soit en Wifi ou via Ethernet. Depuis différents appareils un message d'erreur indique qu'il n'est pas possible de se connecter. En connectant le Raspberry à un écran/clavier j'ai pu redémarrer les services via :
`docker-compose up -d`
Cette solution fonctionne et permet de réparer le problème. Toutefois je me pose la question en cas de campagne sur le terrain sans accès à un matériel informatique, ou bien en présence d'usagers effectuant des relevé et n'ayant pas une connaissance poussé de Postgis. Comment relancer les services dans ces configurations ?
Le Sense Hat est-il une réponse à cette problématique ?
Par ailleurs y a-t-il des explications à ces bugs soudains ? Je me demande si cela n'est pas lié à une sollicitation trop soudaine du Raspberry (trop de connexion d'un coup ou d'usagers effectuant des relevés).

Merci par avance,

Laurian

**Comment by arteragence** [comment]
Pas de souci au niveau de la batterie, elle délivre du 3 A. Par contre peut-être que le fait de toucher au câble usb peut jouer sur la connection (faux contact ou déconnexion involontaire pendant une opération). Dans ce cas le sense hat permet-il de relancer le raspberry sur le terrain ?

**Comment by jancelin** [comment]
je ne developpe plus avec le sensehat.

il y a un service qui check l'etat des containers au démarrage même en cas de débranchement malancontreux.

Attention si un container est stoppé (manuellement principalement), le service ne le redemarrera pas. Juste ceux qui sont en exit.
