### ISSUE TITLE
windows10 tablette et docker-compose

### ISSUE THREAD

**Issue by kamifish** [jancelin/geo-poppy#65]
Bonjour , 

J'utilise Geopoppy depuis quelques temps sans soucis avec des smartphones . 
Nous avons fait l'acquisition d'une tablette pour éviter l'utilisation des smartphones perso et avoir  un meilleur confort de travail. 
Cette tablette est une tablette Getac qui tourne sous windows 10 et là les problèmes commences : impossible d'avoir une géolocalisation.
J'ai vu qu'il un docker-compose "windowsTablette" j'ai donc mis à jour le docker-compose avec ces nouvelles spécifications mais là je n'ai plus accès à l'interface lizmap sur la tablette (Postgresql , le serveur ftp et ssh fonctionne correctement)
Je dois loupé quelque chose mais sans arriver à trouver quoi.

Je vous remercie d'avance .

**Comment by jancelin** [comment]
Microsoft n'a pas prévue dans ses tablettes que l'on puisse utiliser le gps avec un navigateur internet....
Les puces GPS sur tablette windows sont montées sur un port COM via un programme spécifique au constructeur de la puce (souvent ublox).
C'est comme si vous branchez un gps usb sur un PC.

C'est pour ça qu'il est indispensable d'utiliser une tablette android ou apple qui gère nativement la géolocalisation avec un raspberry.

Ou alors passer à géopoppy_android, mais encore quelques developpements pour rendre ça plus simple:
https://github.com/jancelin/geopoppy_android

**Comment by kamifish** [comment]
Bonjour , 
Merci pour votre réponse . Je me sens un peu bête maintenant avec ma tablette Windows . 
J'ai parcouru le dépôt https://github.com/jancelin/geopoppy_android . Mais je n'ai pas trouvé d'équivalent à Userland pour Windows . Cette solution parait supérieur à mon niveau . J'ai contacté le constructeur de la tablette pour savoir si lui connaissait une solution , si c'est le cas je m'empresserai de la partager ici. 
Merci

**Comment by jancelin** [comment]
pas besoin de Userland pour les tablettes windows car il est possible d'installer directement Docker pour créer les services (qgis server / lizmap /postgresql /...).
J'ai aussi une belle Tablette windows ici (hors de prix) avec laquelle je ne peux pas faire grand chose. C'est dommage car les performances d'affichages sont exemplaires mais pas de géolocalisation avec firefox ....
