### ISSUE TITLE
Compatibilité avec le rpi4

### ISSUE THREAD

**Issue by cdaste** [jancelin/geo-poppy#66]
Bonjour,

Geo-poppy est-il compatible avec le nouveau rpi4?

**Comment by jancelin** [comment]
j'attends le mien...
Mais oui, il n'y a pas de raison que non et les 4go de RAM devraient faire des miracles!

à tester!

**Comment by cdaste** [comment]
J'ai essayé de flasher l'image de geopoppy sur ma carte sd, le rpi ne boote pas malheureusement

**Comment by jancelin** [comment]
Le miens arrive la semaine prochaine....
Je vais tester ça.
Merci pour le retour !

**Comment by cdaste** [comment]
Hypriot viens tout juste de sortir pour rpi 4 !

Je teste ça dans la journée, je vous ferez un retour !

**Comment by jancelin** [comment]
je viens de créer une image fonctionelle ( encore 2 trois bugs) bientôt disponible.

**Comment by jancelin** [comment]
note pour plus tard

pour verifier la t°C

sudo echo 'SUBSYSTEM=="vchiq",GROUP="video",MODE="0660"' > /etc/udev/rules.d/10-vchiq-permissions.rules

Après, en tant qu'utilisateur : /opt/vc/bin/vcgencmd measure_temp

**Comment by jancelin** [comment]
@cdaste image en ligne
https://github.com/jancelin/image-builder-rpi/releases/tag/Geopoppy_V0.4.0

mais j'ai un bug wifi avec mon smartphone, disconnect/connect en permanence, pas de problème avec mon pc. A vérifier.

**Comment by cdaste** [comment]
Merci pour l'image, chez moi tout fonctionne nickel même la connexion WIFI avec mon smartphone (un samsung galaxy a70)

**Comment by jancelin** [comment]
Cool, 
Merci pour le retour !

Le problème vient de mon smartphone....
