### ISSUE TITLE
Schéma sans table spatial_ref

### ISSUE THREAD

**Issue by MickaelH974** [jancelin/geo-poppy#7]
Bonjour,

Super travail M. Ancelin.

Je rencontre cependant certains problèmes. Je suis sous Raspberry pi 2 et lors de l'utilisation du contenair PostGIS, à la création de schéma dans des bases spatiales, la table spatial_ref ne se crée pas et les données sont donc stockées sans géométrie.

Aurais-je oublié une étape? Quelqu'un a-t-il le même problème?

En passant il me semble y avoir une erreur dans la doc `chown root:root /home/GeoPoppy/postgres-data` au lieu de `chown root:root /home/GeoPoppy/postgres_data`

Cordialement.

**Comment by jancelin** [comment]
Salut. 

Exact pour le chown. Je corrige. 
Pour la base, je n ai pas re-testé sur pi2 depuis un moment mais ça  m étonne car la construction du container est identique entre les différents modèles de raspberry. 
Dans un premier temps je dirai d arreter et de supprimer le container:
docker-compose stop postgis && docker-compose rm postgis
de supprimer le dossier /9.5 dans /postgres_data puis de relancer le container sans le -d afin de voir ce q u il ce passe.

docker-compose up  postgis

Normalement ça doit reconstruire proprement le template-postgis et la base GIS qui est vide et fonctionnelle.

**Comment by MickaelH974** [comment]
Bonjour M. Ancelin,

Effectivement avec l'option `-d` la construction causait des erreurs et stoppait certains process de construction. Maintenant la construction se poursuit malgré les erreurs de clé des répertoires et autres erreurs non bloquantes. La construction est bien plus longue et tout marche parfaitement.

Merci beaucoup
