### ISSUE TITLE
Besoin mettre à jour la liste des paquets et de mettre à niveau le système avant install wifidirect

### ISSUE THREAD

**Issue by mathieubossaert** [jancelin/geo-poppy#8]
Bonsoir Julien,

petite frayeur à la veille de ma formation ;-)

L'installation en mode fainéant échoue faute de pouvoir installer dnsmaq et hostapd.
Ça se résout bien en lançant un `apt-get update && apt-get upgrade` avant l'installation de Geopoppy.

**Comment by jancelin** [comment]
oups...

merci du retour.

**Comment by jancelin** [comment]
Je viens de modifier le script.
https://github.com/jancelin/rpi_wifi_direct/commit/025334b482a41f6145732f6119fe11111f8e4e0e#diff-5bdf1b2e17ea21fed8e1c8bf77aaec5f

**Comment by mathieubossaert** [comment]
Merci Julien !
