### ISSUE TITLE
Autre léger souci lié aux certificats

### ISSUE THREAD

**Issue by mathieubossaert** [jancelin/geo-poppy#9]
Pour diverses raison (mauvaise date système a priori), les wget échouent.

L'option --no-chek-certificate de wget permet de passer outre, mais sécurise moins...

**Comment by jancelin** [comment]
modifié, plus qu'a tester
https://github.com/jancelin/rpi_wifi_direct/commit/cde18583a45432fddba2fa89a570880b2f0bc122
https://github.com/jancelin/geo-poppy/commit/2443749ae979a959b87bfbdf3b2e08503371a388
https://github.com/jancelin/geo-poppy/commit/9c71388c43674791ace551cd86b98a9a0e48c59

**Comment by mathieubossaert** [comment]
Je teste dans la semaine, refaisant une install fraiche. Mathieu

**Comment by bobo-romania** [comment]
Salut, l'utilisation de l'option --no-check-certificate me semble pas être à la bonne place.
cela créé un fichier --no-check-certificate.
et ça se bloque directement.
De ce que j'ai pu tester, cela marche quand l'option 
"--no-check-certificate" est inscrite avant l'option "-P" 

![bureau](https://cloud.githubusercontent.com/assets/3932557/18954718/7c485b5e-8654-11e6-9243-e1209ed1081b.png)

**Comment by mathieubossaert** [comment]
Bonjour, oui je n'ai pas fait attention aux modifications de Julien : 
La bonne syntaxe est bien `wget --no-check-certificate -P /home/pirate...`

**Comment by jancelin** [comment]
Merci les debuggers.
La modif est faite, vous pouvez tester.

Pour les bon élèves un petit bonus en test, j'ai pushé deux images sur dockerhub pour avoir une install stable et constante (contrairement au docker run et divers problèmes de dépendances du dépot debian sid).
https://hub.docker.com/r/jancelin/geopoppy/
``` 
docker pull docker pull jancelin/geopoppy:qgis-lizmap
docker pull docker pull jancelin/geopoppy:postgis
```

vous pouvez enfin modifier votre docker-compose.yml en changeant les lignes:
``` 
nano /home/pirate/docker-compose.yml

build: git://github.com/jancelin/rpi-docker-lizmap
build: git://github.com/jancelin/docker-postgis-rpi
```
par
```
image: jancelin/geopoppy:qgis-lizmap
image:  jancelin/geopoppy: postgis
```
et faire un
```
docker-compose up -d
```
vous aurez maintenant postgresl 9.5, postgis 2.2 qgis-serveur 2.14.6 et le dernier lizmap 3.0.3 en téléchargement stable

mais chut, c'est encore en test... j'espère avoir vos retours.

**Comment by mathieubossaert** [comment]
Je fais un test pour le 5 en y ajoutant une couche OpenDataKit ;-)
https://hub.docker.com/r/sicenlr/raspberry-odk/

**Comment by jancelin** [comment]
stand by, je re-test l'install

**Comment by mathieubossaert** [comment]
Bonjour Julien, 
je teste aujourd'hui.

**Comment by bobo-romania** [comment]
Ce moment...
quand tu tapes 192.168.1.16
![rpi](https://cloud.githubusercontent.com/assets/3932557/18986266/673a186c-86fc-11e6-84b8-3121bab20c75.png)
![lizmap](https://cloud.githubusercontent.com/assets/3932557/18986268/690a2df8-86fc-11e6-87a2-1fc82ea073a2.png)

**Comment by mathieubossaert** [comment]
;-)

**Comment by jancelin** [comment]
youou :)

**Comment by jancelin** [comment]
après un push sur le dockerhub, lizmap à l'air de fonctionner correctement au premier boot sur le wifi.

**Comment by jancelin** [comment]
j'ai remodifié lizmap car apache avait un problème de PID. ça devrais résoudre le problème.

https://github.com/jancelin/rpi-docker-lizmap/commit/3a74b3e093d8a8736abf459c91481e9483a8438

il ne reste plus qu'a refabriquer l'image:
```docker pull jancelin/geopoppy:qgis-lizmap```

**Comment by jancelin** [comment]
je ferme si vous n'y voyez pas inconvénients...
